import type { ModelDefinition, ProviderDefinition } from "./schema";

export const providers: ProviderDefinition[] = [
  {
    id: "anthill",
    name: "Anthill Code",
    shortName: "ANT",
    description: "Careful plans, literary model names, and a mysteriously emotional quota meter.",
    color: "#d49b78",
    maxQuota: 100,
    regenPerSecond: 0.022,
    unlockAfter: 0,
  },
  {
    id: "openmind",
    name: "OpenMind Forge",
    shortName: "OMF",
    description: "Isolated workspaces, adjustable confidence, and an enthusiasm for doing all of it at once.",
    color: "#72d7c3",
    maxQuota: 90,
    regenPerSecond: 0.03,
    unlockAfter: 0,
  },
];

export const models: ModelDefinition[] = [
  {
    id: "couplet",
    providerId: "anthill",
    name: "Couplet",
    tier: "quick",
    description: "Fast and frugal. Ideal when the answer should fit in two lines.",
    speed: 1.35,
    quotaRate: 0.042,
    riskModifier: 0.12,
    contextDecay: 0.052,
    unlockTrust: 0,
  },
  {
    id: "ballad",
    providerId: "anthill",
    name: "Ballad",
    tier: "balanced",
    description: "The dependable default for features, tests, and medium-sized regrets.",
    speed: 1,
    quotaRate: 0.06,
    riskModifier: -0.04,
    contextDecay: 0.036,
    unlockTrust: 0,
  },
  {
    id: "epic",
    providerId: "anthill",
    name: "Epic",
    tier: "deep",
    description: "Excellent architecture. Uses quota as though someone else is paying.",
    speed: 0.78,
    quotaRate: 0.105,
    riskModifier: -0.19,
    contextDecay: 0.025,
    unlockTrust: 50,
  },
  {
    id: "spark",
    providerId: "openmind",
    name: "Spark",
    tier: "quick",
    description: "Cheap parallel execution with a tendency to declare victory early.",
    speed: 1.5,
    quotaRate: 0.047,
    riskModifier: 0.15,
    contextDecay: 0.06,
    unlockTrust: 0,
  },
  {
    id: "forge",
    providerId: "openmind",
    name: "Forge",
    tier: "balanced",
    description: "A capable autonomous worker with strong tool use and reasonable restraint.",
    speed: 1.08,
    quotaRate: 0.064,
    riskModifier: -0.05,
    contextDecay: 0.04,
    unlockTrust: 42,
  },
  {
    id: "foundry",
    providerId: "openmind",
    name: "Foundry",
    tier: "deep",
    description: "For migrations, outages, and prompts that begin with “this is subtle.”",
    speed: 0.82,
    quotaRate: 0.112,
    riskModifier: -0.21,
    contextDecay: 0.027,
    unlockTrust: 62,
  },
];
