import type { TicketDefinition } from "./schema";

export const tickets: TicketDefinition[] = [
  {
    id: "deployment-banner",
    key: "APP-101",
    title: "Rename the deployment banner",
    summary: "Marketing discovered sentence case. Update the staging banner before stand-up.",
    brief: "Change the staging banner copy and leave production untouched.",
    kind: "chore",
    duration: 180,
    baseRisk: 0.08,
    rewardTrust: 8,
    prerequisites: [],
    recommendedTier: "quick",
    files: ["ui/Banner.tsx", "ui/banner.test.tsx"],
    evidence: {
      summary: "Changed one label and its snapshot.",
      tests: "12 UI checks passed.",
      signal: "The production condition remains unchanged.",
    },
    riskFlag: "none",
  },
  {
    id: "telemetry-toggle",
    key: "APP-118",
    title: "Add a usage telemetry toggle",
    summary: "Enterprise wants an off switch. Product has not said what the default should be.",
    brief: "Add a workspace setting, persist it, and make the default explicit.",
    kind: "feature",
    duration: 260,
    baseRisk: 0.3,
    rewardTrust: 10,
    prerequisites: ["deployment-banner"],
    recommendedTier: "balanced",
    files: ["settings/PrivacyPanel.tsx", "settings/workspace.ts", "api/telemetry.ts"],
    evidence: {
      summary: "Added a stored workspace preference and guarded the event sender.",
      tests: "Unit checks pass; no migration fixture was added.",
      signal: "The generated default is enabled unless the brief says otherwise.",
    },
    riskFlag: "privacy-default",
  },
  {
    id: "cache-summary",
    key: "PERF-204",
    title: "Cache the dashboard summary",
    summary: "The dashboard is slow during demos. Cache it without showing stale customer data.",
    brief: "Cache summary reads and invalidate them whenever a customer record changes.",
    kind: "platform",
    duration: 330,
    baseRisk: 0.42,
    rewardTrust: 12,
    prerequisites: ["deployment-banner"],
    recommendedTier: "balanced",
    files: ["dashboard/summary.ts", "customers/repository.ts", "cache/keys.ts"],
    evidence: {
      summary: "Added a five-minute cache around dashboard reads.",
      tests: "Fast checks pass; mutation paths are not covered.",
      signal: "The diff adds cache writes but no obvious invalidation call.",
    },
    riskFlag: "cache-shortcut",
  },
  {
    id: "runtime-upgrade",
    key: "PLAT-77",
    title: "Upgrade the session runtime",
    summary: "Security needs the supported runtime before Friday's audit.",
    brief: "Upgrade the runtime, regenerate the lockfile, and verify worker startup.",
    kind: "platform",
    duration: 360,
    baseRisk: 0.36,
    rewardTrust: 13,
    prerequisites: ["telemetry-toggle"],
    recommendedTier: "deep",
    files: ["package.json", "bun.lock", "workers/session.ts"],
    evidence: {
      summary: "Updated the runtime target and regenerated dependencies.",
      tests: "Application checks pass; worker smoke test was skipped.",
      signal: "One worker still imports a compatibility shim marked legacy.",
    },
    riskFlag: "runtime-drift",
  },
  {
    id: "parallel-reports",
    key: "DATA-312",
    title: "Parallelise report generation",
    summary: "Run account reports concurrently without double-writing the shared export.",
    brief: "Use isolated jobs, preserve ordering, and make the final write atomic.",
    kind: "feature",
    duration: 420,
    baseRisk: 0.48,
    rewardTrust: 15,
    prerequisites: ["cache-summary", "runtime-upgrade"],
    recommendedTier: "deep",
    files: ["reports/runner.ts", "reports/export.ts", "queue/worker.ts"],
    evidence: {
      summary: "Runs report jobs concurrently and joins results before export.",
      tests: "Concurrency test passed 9 of 10 repeated runs.",
      signal: "The shared filename is constructed before job isolation.",
    },
    riskFlag: "merge-race",
  },
  {
    id: "quota-display",
    key: "UI-229",
    title: "Fix the quota display",
    summary: "The meter says 3% while the provider says 97%. Nobody agrees which side is full.",
    brief: "Normalise provider usage values and label whether the meter shows used or remaining capacity.",
    kind: "bug",
    duration: 240,
    baseRisk: 0.2,
    rewardTrust: 9,
    prerequisites: ["telemetry-toggle"],
    recommendedTier: "quick",
    files: ["usage/normalise.ts", "ui/QuotaMeter.tsx"],
    evidence: {
      summary: "Normalised both provider formats to remaining capacity.",
      tests: "All provider fixtures pass.",
      signal: "Naming is explicit at each conversion boundary.",
    },
    riskFlag: "none",
  },
  {
    id: "stale-customer-data",
    key: "INC-1",
    title: "Investigate stale customer data",
    summary: "Support reports that edited customer names remain stale on the executive dashboard.",
    brief: "Trace the stale-read path, restore correctness, and add a regression check.",
    kind: "bug",
    duration: 360,
    baseRisk: 0.34,
    rewardTrust: 18,
    prerequisites: ["parallel-reports", "quota-display"],
    recommendedTier: "deep",
    files: ["dashboard/summary.ts", "customers/repository.ts", "cache/invalidation.test.ts"],
    evidence: {
      summary: "Invalidates customer summary keys after every committed mutation.",
      tests: "Regression test reproduces the incident and now passes.",
      signal: "The root cause points back to PERF-204's review decision.",
    },
    riskFlag: "none",
  },
  {
    id: "investor-demo",
    key: "SHIP-1",
    title: "Ship the investor demo",
    summary: "The room is booked. Decide what quality means with eight minutes left.",
    brief: "Cut a stable release candidate, document known risks, and preserve rollback.",
    kind: "finale",
    duration: 480,
    baseRisk: 0.5,
    rewardTrust: 24,
    prerequisites: ["stale-customer-data"],
    recommendedTier: "deep",
    files: ["release/manifest.ts", "ops/rollback.md", "CHANGELOG.md"],
    evidence: {
      summary: "Built the release candidate and recorded unresolved risks.",
      tests: "Critical path passes; confidence depends on accumulated repository health.",
      signal: "This is the last review. Your history is part of the diff.",
    },
    riskFlag: "none",
  },
];
